name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
