name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - main

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1'  # Use a compatible R version

    - name: Install dependencies
      run: |
        R -e 'install.packages(c("covr", "testthat"))'
        R -e 'devtools::install_deps(dependencies = TRUE)'

   - name: Run tests and coverage
      run: |
        R CMD build .
        R CMD check *tar.gz
        R -e 'covr::package_coverage()'
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: '*covr*'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
